version: '3.7'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=MY_Store
      - POSTGRES_USER=EduardMartGlez
      - POSTGRES_PASSWORD=dejame
    ports:
    - 5432:5432
    # volumes:
    # - ./postgres_data:/var/lib/postgresql/data
  #  pgadmin: dpage/pgadmin
  #  environment:
  #  - PGADMIN_DEFAULT_EMAIL=
  #   - PGADMIN_DEFAULT_PASSWORD=
  #   ports:
  #   -""
