version: '3.7'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=MY_Store
      - POSTGRES_USER=EduardMartGlez
      - POSTGRES_PASSWORD=dejame
    ports:
    - 5432:5432
    volumes:
     - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
     - 5050:80
