version: '3.7'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_HOST= 127.0.0.1
      - POSTGRES_DB=Store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dejame
    ports:
    - 5432:5432
    # volumes:
    # - ./postgres_data:/var/lib/postgresql/data
  # pgadmin: dpage/pgadmin
  # environment:
  #  - PGADMIN_DEFAULT_EMAIL=
  #  - PGADMIN_DEFAULT_PASSWORD
